-- MySQL Script generated by MySQL Workbench
-- Fri Jun  7 11:01:01 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema certificadodb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema certificadodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `certificadodb` DEFAULT CHARACTER SET utf8 ;
USE `certificadodb` ;

-- -----------------------------------------------------
-- Table `certificadodb`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `certificadodb`.`pessoa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `certificadodb`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `certificadodb`.`evento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(250) NOT NULL,
  `data_inicio` VARCHAR(45) NOT NULL,
  `carga_horaria` VARCHAR(45) NOT NULL,
  `descricao` TEXT(1000) NOT NULL,
  `observacao` TEXT(1000) NULL,
  `data_fim` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `certificadodb`.`certificado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `certificadodb`.`certificado` (
  `validador` VARCHAR(45) NOT NULL,
  `pessoa_id` INT NOT NULL,
  `evento_id` INT NOT NULL,
  `tipo_participacao` VARCHAR(45) NOT NULL,
  INDEX `fk_certificado_pessoa_idx` (`pessoa_id` ASC) ,
  INDEX `fk_certificado_evento1_idx` (`evento_id` ASC) ,
  PRIMARY KEY (`pessoa_id`, `evento_id`),
  CONSTRAINT `fk_certificado_pessoa`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `certificadodb`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_certificado_evento1`
    FOREIGN KEY (`evento_id`)
    REFERENCES `certificadodb`.`evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `certificadodb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `certificadodb`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO `certificadodb`.`usuario` (`nome`, `usuario`, `senha`)
VALUES ('admin', 'admin', md5('admin'));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
